# 1. Database Connectivity Parameters
spring.datasource.url=jdbc:postgresql://localhost:5432/apexledger_db
spring.datasource.username=postgres
spring.datasource.password=pass12@#

# Explicitly tell Spring to use the PostgreSQL Driver class
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate/JPA Automation Engine Layout
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
